---
version: "3.9"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - warvolume:/tmp/docker/

  starter:
    image: tomcat:9
    ports:
      - "8081:8080"
    volumes_from:
      - builder
    command: >
      bash -c  "cp /tmp/docker/hello-1.0.war /var/lib/tomcat9/webapps/
      && catalina.sh run"

volumes:
  warvolume:
