---
version: "3.9"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    command: cp /boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/docker/
    volumes:
      - warvolume:/tmp/docker/

  starter:
    image: tomcat:9
    ports:
      - "8081:8080"
    volumes:
      - warvolume:/var/lib/tomcat9/webapps/
    command: ["catalina.sh", "run"]

volumes:
  warvolume: